package com.example.android.miwok;

import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.util.Log;
import android.widget.LinearLayout;
import android.widget.TextView;

import java.util.ArrayList;
import java.util.concurrent.locks.Condition;

public class NumbersActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_numbers);

        //Create an array of words
        ArrayList<String> words = new ArrayList<>();
        words.add("one");
        words.add("two");
        words.add("three");
        words.add("four");
        words.add("five");
        words.add("six");
        words.add("seven");
        words.add("eight");
        words.add("nine");
        words.add("ten");
        words.add("eleven");
        words.add("twelve");
        words.add("thirteen");
        words.add("fourteen");
        words.add("fifteen");
        words.add("sixteen");
        words.add("seventeen");
        words.add("eighteen");
        words.add("nineteen");
        words.add("twenty");
        words.add("twenty-one");
        words.add("twenty-Two");
        words.add("twenty-Three");
        words.add("twenty-Four");
        words.add("twenty-Five");
        words.add("twenty-Six");
        words.add("twenty-Seven");
        words.add("twenty-Eight");
        words.add("twenty-Nine");
        words.add("thirty");
        words.add("thirty-One");
        words.add("thirty-Two");
        words.add("thirty-Three");
        words.add("thirty-Four");
        words.add("thirty-Five");
        words.add("thirty-Six");
        words.add("thirty-Seven");
        words.add("thirty-Eight");
        words.add("thirty-Nine");
        words.add("forty");
        words.add("forty-One");
        words.add("forty-Two");
        words.add("forty-Three");
        words.add("forty-Four");
        words.add("forty-Five");
        words.add("forty-Six");
        words.add("forty-Seven");
        words.add("forty-Eight");
        words.add("forty-Nine");
        words.add("fifty");
        words.add("fifty-One");
        words.add("fifty-Two");
        words.add("fifty-Three");
        words.add("fifty-Four");
        words.add("fifty-Five");
        words.add("fifty-Six");
        words.add("fifty-Seven");
        words.add("fifty-Eight");
        words.add("fifty-Nine");
        words.add("Sixty");
        words.add("Sixty-One");
        words.add("Sixty-Two");
        words.add("Sixty-Three");
        words.add("Sixty-Four");
        words.add("Sixty-Five");
        words.add("Sixty-Six");
        words.add("Sixty-Seven");
        words.add("Sixty-Eight");
        words.add("Sixty-Nine");
        words.add("Seventy");
        words.add("Seventy-One");
        words.add("Seventy-Two");
        words.add("Seventy-Three");
        words.add("Seventy-Four");
        words.add("Seventy-Five");
        words.add("Seventy-Six");
        words.add("Seventy-Seven");
        words.add("Seventy-Eight");
        words.add("Seventy-Nine");
        words.add("eighty");
        words.add("eighty-One");
        words.add("eighty-Two");
        words.add("eighty-Three");
        words.add("eighty-Four");
        words.add("eighty-Five");
        words.add("eighty-Six");
        words.add("eighty-Seven");
        words.add("eighty-Eight");
        words.add("eighty-Nine");
        words.add("Ninety");
        words.add("Ninety-One");
        words.add("Ninety-Two");
        words.add("Ninety-Three");
        words.add("Ninety-Four");
        words.add("Ninety-Five");
        words.add("Ninety-Six");
        words.add("Ninety-Seven");
        words.add("Ninety-Eight");
        words.add("Ninety-Nine");
        words.add("One hundred");
        words.add("One hundred One");
        words.add("One hundred Two");
        words.add("One hundred Three");
        words.add("One hundred Four");
        words.add("One hundred Five");
        words.add("One hundred Six");
        words.add("One hundred Seven");
        words.add("One hundred Eight");
        words.add("One hundred Nine");
        words.add("One hundred ten");
        words.add("One hundred eleven");
        words.add("One hundred twelve");
        words.add("One hundred thirteen");
        words.add("One hundred Fourteen");
        words.add("One hundred fifteen");
        words.add("One hundred Sixteen");
        words.add("One hundred Seventeen");
        words.add("One hundred eighteen");
        words.add("One hundred Nineteen");
        words.add("One hundred twenty");
        words.add("One hundred twenty-One");
        words.add("One hundred twenty-Two");
        words.add("One hundred twenty-Three");
        words.add("One hundred twenty-Four");
        words.add("One hundred twenty-Five");
        words.add("One hundred twenty-Six");
        words.add("One hundred twenty-Seven");
        words.add("One hundred twenty-Eight");
        words.add("One hundred twenty-Nine");
        words.add("One hundred thirty");
        words.add("One hundred thirty-One");
        words.add("One hundred thirty-Two");
        words.add("One hundred thirty-Three");
        words.add("One hundred thirty-Four");
        words.add("One hundred thirty-Five");
        words.add("One hundred thirty-Six");
        words.add("One hundred thirty-Seven");
        words.add("One hundred thirty-Eight");
        words.add("One hundred thirty-Nine");
        words.add("One hundred forty");
        words.add("One hundred forty-One");
        words.add("One hundred forty-Two");
        words.add("One hundred forty-Three");
        words.add("One hundred forty-Four");
        words.add("One hundred forty-Five");
        words.add("One hundred forty-Six");
        words.add("One hundred forty-Seven");
        words.add("One hundred forty-Eight");
        words.add("One hundred forty-Nine");
        words.add("One hundred fifty");
        words.add("One hundred fifty-One");
        words.add("One hundred fifty-Two");
        words.add("One hundred fifty-Three");
        words.add("One hundred fifty-Four");
        words.add("One hundred fifty-Five");
        words.add("One hundred fifty-Six");
        words.add("One hundred fifty-Seven");
        words.add("One hundred fifty-Eight");
        words.add("One hundred fifty-Nine");
        words.add("One hundred Sixty");
        words.add("One hundred Sixty-One");
        words.add("One hundred Sixty-Two");
        words.add("One hundred Sixty-Three");
        words.add("One hundred Sixty-Four");
        words.add("One hundred Sixty-Five");
        words.add("One hundred Sixty-Six");
        words.add("One hundred Sixty-Seven");
        words.add("One hundred Sixty-Eight");
        words.add("One hundred Sixty-Nine");
        words.add("One hundred Seventy");
        words.add("One hundred Seventy-One");
        words.add("One hundred Seventy-Two");
        words.add("One hundred Seventy-Three");
        words.add("One hundred Seventy-Four");
        words.add("One hundred Seventy-Five");
        words.add("One hundred Seventy-Six");
        words.add("One hundred Seventy-Seven");
        words.add("One hundred Seventy-Eight");
        words.add("One hundred Seventy-Nine");
        words.add("One hundred eighty");
        words.add("One hundred eighty-One");
        words.add("One hundred eighty-Two");
        words.add("One hundred eighty-Three");
        words.add("One hundred eighty-Four");
        words.add("One hundred eighty-Five");
        words.add("One hundred eighty-Six");
        words.add("One hundred eighty-Seven");
        words.add("One hundred eighty-Eight");
        words.add("One hundred eighty-Nine");
        words.add("One hundred Ninety");
        words.add("One hundred Ninety-One");
        words.add("One hundred Ninety-Two");
        words.add("One hundred Ninety-Three");
        words.add("One hundred Ninety-Four");
        words.add("One hundred Ninety-Five");
        words.add("One hundred Ninety-Six");
        words.add("One hundred Ninety-Seven");
        words.add("One hundred Ninety-Eight");
        words.add("One hundred Ninety-Nine");
        words.add("Two hundred");
        words.add("Two hundred One");
        words.add("Two hundred Two");
        words.add("Two hundred Three");
        words.add("Two hundred Four");
        words.add("Two hundred Five");
        words.add("Two hundred Six");
        words.add("Two hundred Seven");
        words.add("Two hundred Eight");
        words.add("Two hundred Nine");
        words.add("Two hundred ten");
        words.add("Two hundred eleven");
        words.add("Two hundred twelve");
        words.add("Two hundred thirteen");
        words.add("Two hundred Fourteen");
        words.add("Two hundred fifteen");
        words.add("Two hundred Sixteen");
        words.add("Two hundred Seventeen");
        words.add("Two hundred eighteen");
        words.add("Two hundred Nineteen");
        words.add("Two hundred twenty");
        words.add("Two hundred twenty-One");
        words.add("Two hundred twenty-Two");
        words.add("Two hundred twenty-Three");
        words.add("Two hundred twenty-Four");
        words.add("Two hundred twenty-Five");
        words.add("Two hundred twenty-Six");
        words.add("Two hundred twenty-Seven");
        words.add("Two hundred twenty-Eight");
        words.add("Two hundred twenty-Nine");
        words.add("Two hundred thirty");
        words.add("Two hundred thirty-One");
        words.add("Two hundred thirty-Two");
        words.add("Two hundred thirty-Three");
        words.add("Two hundred thirty-Four");
        words.add("Two hundred thirty-Five");
        words.add("Two hundred thirty-Six");
        words.add("Two hundred thirty-Seven");
        words.add("Two hundred thirty-Eight");
        words.add("Two hundred thirty-Nine");
        words.add("Two hundred forty");
        words.add("Two hundred forty-One");
        words.add("Two hundred forty-Two");
        words.add("Two hundred forty-Three");
        words.add("Two hundred forty-Four");
        words.add("Two hundred forty-Five");
        words.add("Two hundred forty-Six");
        words.add("Two hundred forty-Seven");
        words.add("Two hundred forty-Eight");
        words.add("Two hundred forty-Nine");
        words.add("Two hundred fifty");
        words.add("Two hundred fifty-One");
        words.add("Two hundred fifty-Two");
        words.add("Two hundred fifty-Three");
        words.add("Two hundred fifty-Four");
        words.add("Two hundred fifty-Five");
        words.add("Two hundred fifty-Six");
        words.add("Two hundred fifty-Seven");
        words.add("Two hundred fifty-Eight");
        words.add("Two hundred fifty-Nine");
        words.add("Two hundred Sixty");
        words.add("Two hundred Sixty-One");
        words.add("Two hundred Sixty-Two");
        words.add("Two hundred Sixty-Three");
        words.add("Two hundred Sixty-Four");
        words.add("Two hundred Sixty-Five");
        words.add("Two hundred Sixty-Six");
        words.add("Two hundred Sixty-Seven");
        words.add("Two hundred Sixty-Eight");
        words.add("Two hundred Sixty-Nine");
        words.add("Two hundred Seventy");
        words.add("Two hundred Seventy-One");
        words.add("Two hundred Seventy-Two");
        words.add("Two hundred Seventy-Three");
        words.add("Two hundred Seventy-Four");
        words.add("Two hundred Seventy-Five");
        words.add("Two hundred Seventy-Six");
        words.add("Two hundred Seventy-Seven");
        words.add("Two hundred Seventy-Eight");
        words.add("Two hundred Seventy-Nine");
        words.add("Two hundred eighty");
        words.add("Two hundred eighty-One");
        words.add("Two hundred eighty-Two");
        words.add("Two hundred eighty-Three");
        words.add("Two hundred eighty-Four");
        words.add("Two hundred eighty-Five");
        words.add("Two hundred eighty-Six");
        words.add("Two hundred eighty-Seven");
        words.add("Two hundred eighty-Eight");
        words.add("Two hundred eighty-Nine");
        words.add("Two hundred Ninety");
        words.add("Two hundred Ninety-One");
        words.add("Two hundred Ninety-Two");
        words.add("Two hundred Ninety-Three");
        words.add("Two hundred Ninety-Four");
        words.add("Two hundred Ninety-Five");
        words.add("Two hundred Ninety-Six");
        words.add("Two hundred Ninety-Seven");
        words.add("Two hundred Ninety-Eight");
        words.add("Two hundred Ninety-Nine");
        words.add("Three hundred");
        words.add("Three hundred One");
        words.add("Three hundred Two");
        words.add("Three hundred Three");
        words.add("Three hundred Four");
        words.add("Three hundred Five");
        words.add("Three hundred Six");
        words.add("Three hundred Seven");
        words.add("Three hundred Eight");
        words.add("Three hundred Nine");
        words.add("Three hundred ten");
        words.add("Three hundred eleven");
        words.add("Three hundred twelve");
        words.add("Three hundred thirteen");
        words.add("Three hundred Fourteen");
        words.add("Three hundred fifteen");
        words.add("Three hundred Sixteen");
        words.add("Three hundred Seventeen");
        words.add("Three hundred eighteen");
        words.add("Three hundred Nineteen");
        words.add("Three hundred twenty");
        words.add("Three hundred twenty-One");
        words.add("Three hundred twenty-Two");
        words.add("Three hundred twenty-Three");
        words.add("Three hundred twenty-Four");
        words.add("Three hundred twenty-Five");
        words.add("Three hundred twenty-Six");
        words.add("Three hundred twenty-Seven");
        words.add("Three hundred twenty-Eight");
        words.add("Three hundred twenty-Nine");
        words.add("Three hundred thirty");
        words.add("Three hundred thirty-One");
        words.add("Three hundred thirty-Two");
        words.add("Three hundred thirty-Three");
        words.add("Three hundred thirty-Four");
        words.add("Three hundred thirty-Five");
        words.add("Three hundred thirty-Six");
        words.add("Three hundred thirty-Seven");
        words.add("Three hundred thirty-Eight");
        words.add("Three hundred thirty-Nine");
        words.add("Three hundred forty");
        words.add("Three hundred forty-One");
        words.add("Three hundred forty-Two");
        words.add("Three hundred forty-Three");
        words.add("Three hundred forty-Four");
        words.add("Three hundred forty-Five");
        words.add("Three hundred forty-Six");
        words.add("Three hundred forty-Seven");
        words.add("Three hundred forty-Eight");
        words.add("Three hundred forty-Nine");
        words.add("Three hundred fifty");
        words.add("Three hundred fifty-One");
        words.add("Three hundred fifty-Two");
        words.add("Three hundred fifty-Three");
        words.add("Three hundred fifty-Four");
        words.add("Three hundred fifty-Five");
        words.add("Three hundred fifty-Six");
        words.add("Three hundred fifty-Seven");
        words.add("Three hundred fifty-Eight");
        words.add("Three hundred fifty-Nine");
        words.add("Three hundred Sixty");
        words.add("Three hundred Sixty-One");
        words.add("Three hundred Sixty-Two");
        words.add("Three hundred Sixty-Three");
        words.add("Three hundred Sixty-Four");
        words.add("Three hundred Sixty-Five");
        words.add("Three hundred Sixty-Six");
        words.add("Three hundred Sixty-Seven");
        words.add("Three hundred Sixty-Eight");
        words.add("Three hundred Sixty-Nine");
        words.add("Three hundred Seventy");
        words.add("Three hundred Seventy-One");
        words.add("Three hundred Seventy-Two");
        words.add("Three hundred Seventy-Three");
        words.add("Three hundred Seventy-Four");
        words.add("Three hundred Seventy-Five");
        words.add("Three hundred Seventy-Six");
        words.add("Three hundred Seventy-Seven");
        words.add("Three hundred Seventy-Eight");
        words.add("Three hundred Seventy-Nine");
        words.add("Three hundred eighty");
        words.add("Three hundred eighty-One");
        words.add("Three hundred eighty-Two");
        words.add("Three hundred eighty-Three");
        words.add("Three hundred eighty-Four");
        words.add("Three hundred eighty-Five");
        words.add("Three hundred eighty-Six");
        words.add("Three hundred eighty-Seven");
        words.add("Three hundred eighty-Eight");
        words.add("Three hundred eighty-Nine");
        words.add("Three hundred Ninety");
        words.add("Three hundred Ninety-One");
        words.add("Three hundred Ninety-Two");
        words.add("Three hundred Ninety-Three");
        words.add("Three hundred Ninety-Four");
        words.add("Three hundred Ninety-Five");
        words.add("Three hundred Ninety-Six");
        words.add("Three hundred Ninety-Seven");
        words.add("Three hundred Ninety-Eight");
        words.add("Three hundred Ninety-Nine");
        words.add("Four hundred");
        words.add("Four hundred One");
        words.add("Four hundred Two");
        words.add("Four hundred Three");
        words.add("Four hundred Four");
        words.add("Four hundred Five");
        words.add("Four hundred Six");
        words.add("Four hundred Seven");
        words.add("Four hundred Eight");
        words.add("Four hundred Nine");
        words.add("Four hundred ten");
        words.add("Four hundred eleven");
        words.add("Four hundred twelve");
        words.add("Four hundred thirteen");
        words.add("Four hundred Fourteen");
        words.add("Four hundred fifteen");
        words.add("Four hundred Sixteen");
        words.add("Four hundred Seventeen");
        words.add("Four hundred eighteen");
        words.add("Four hundred Nineteen");
        words.add("Four hundred twenty");
        words.add("Four hundred twenty-One");
        words.add("Four hundred twenty-Two");
        words.add("Four hundred twenty-Three");
        words.add("Four hundred twenty-Four");
        words.add("Four hundred twenty-Five");
        words.add("Four hundred twenty-Six");
        words.add("Four hundred twenty-Seven");
        words.add("Four hundred twenty-Eight");
        words.add("Four hundred twenty-Nine");
        words.add("Four hundred thirty");
        words.add("Four hundred thirty-One");
        words.add("Four hundred thirty-Two");
        words.add("Four hundred thirty-Three");
        words.add("Four hundred thirty-Four");
        words.add("Four hundred thirty-Five");
        words.add("Four hundred thirty-Six");
        words.add("Four hundred thirty-Seven");
        words.add("Four hundred thirty-Eight");
        words.add("Four hundred thirty-Nine");
        words.add("Four hundred forty");
        words.add("Four hundred forty-One");
        words.add("Four hundred forty-Two");
        words.add("Four hundred forty-Three");
        words.add("Four hundred forty-Four");
        words.add("Four hundred forty-Five");
        words.add("Four hundred forty-Six");
        words.add("Four hundred forty-Seven");
        words.add("Four hundred forty-Eight");
        words.add("Four hundred forty-Nine");
        words.add("Four hundred fifty");
        words.add("Four hundred fifty-One");
        words.add("Four hundred fifty-Two");
        words.add("Four hundred fifty-Three");
        words.add("Four hundred fifty-Four");
        words.add("Four hundred fifty-Five");
        words.add("Four hundred fifty-Six");
        words.add("Four hundred fifty-Seven");
        words.add("Four hundred fifty-Eight");
        words.add("Four hundred fifty-Nine");
        words.add("Four hundred Sixty");
        words.add("Four hundred Sixty-One");
        words.add("Four hundred Sixty-Two");
        words.add("Four hundred Sixty-Three");
        words.add("Four hundred Sixty-Four");
        words.add("Four hundred Sixty-Five");
        words.add("Four hundred Sixty-Six");
        words.add("Four hundred Sixty-Seven");
        words.add("Four hundred Sixty-Eight");
        words.add("Four hundred Sixty-Nine");
        words.add("Four hundred Seventy");
        words.add("Four hundred Seventy");
        words.add("Four hundred Seventy-One");
        words.add("Four hundred Seventy-Three");
        words.add("Four hundred Seventy-Four");
        words.add("Four hundred Seventy-Five");
        words.add("Four hundred Seventy-Six");
        words.add("Four hundred Seventy-Seven");
        words.add("Four hundred Seventy-Eight");
        words.add("Four hundred Seventy-Nine");
        words.add("Four hundred eighty");
        words.add("Four hundred eighty-One");
        words.add("Four hundred eighty-Two");
        words.add("Four hundred eighty-Three");
        words.add("Four hundred eighty-Four");
        words.add("Four hundred eighty-Five");
        words.add("Four hundred eighty-Six");
        words.add("Four hundred eighty-Seven");
        words.add("Four hundred eighty-Eight");
        words.add("Four hundred eighty-Nine");
        words.add("Four hundred Ninety");
        words.add("Four hundred Ninety-One");
        words.add("Four hundred Ninety-Two");
        words.add("Four hundred Ninety-Three");
        words.add("Four hundred Ninety-Four");
        words.add("Four hundred Ninety-Five");
        words.add("Four hundred Ninety-Six");
        words.add("Four hundred Ninety-Seven");
        words.add("Four hundred Ninety-Eight");
        words.add("Four hundred Ninety-Nine");
        words.add("Five hundred");
        words.add("Five hundred One");
        words.add("Five hundred Two");
        words.add("Five hundred Three");
        words.add("Five hundred Four");
        words.add("Five hundred Five");
        words.add("Five hundred Six");
        words.add("Five hundred Seven");
        words.add("Five hundred Eight");
        words.add("Five hundred Nine");
        words.add("Five hundred ten");
        words.add("Five hundred eleven");
        words.add("Five hundred twelve");
        words.add("Five hundred thirteen");
        words.add("Five hundred Fourteen");
        words.add("Five hundred fifteen");
        words.add("Five hundred Sixteen");
        words.add("Five hundred Seventeen");
        words.add("Five hundred eighteen");
        words.add("Five hundred Nineteen");
        words.add("Five hundred twenty");
        words.add("Five hundred twenty-One");
        words.add("Five hundred twenty-Two");
        words.add("Five hundred twenty-Three");
        words.add("Five hundred twenty-Four");
        words.add("Five hundred twenty-Five");
        words.add("Five hundred twenty-Six");
        words.add("Five hundred twenty-Seven");
        words.add("Five hundred twenty-Eight");
        words.add("Five hundred twenty-Nine");
        words.add("Five hundred thirty");
        words.add("Five hundred thirty-One");
        words.add("Five hundred thirty-Two");
        words.add("Five hundred thirty-Three");
        words.add("Five hundred thirty-Three");
        words.add("Five hundred thirty-Five");
        words.add("Five hundred thirty-Six");
        words.add("Five hundred thirty-Seven");
        words.add("Five hundred thirty-Eight");
        words.add("Five hundred thirty-Nine");
        words.add("Five hundred forty");
        words.add("Five hundred forty-One");
        words.add("Five hundred forty-Two");
        words.add("Five hundred forty-Three");
        words.add("Five hundred forty-Four");
        words.add("Five hundred forty-Five");
        words.add("Five hundred forty-Six");
        words.add("Five hundred forty-Seven");
        words.add("Five hundred forty-Eight");
        words.add("Five hundred forty-Nine");
        words.add("Five hundred fifty");
        words.add("Five hundred fifty-One");
        words.add("Five hundred fifty-Two");
        words.add("Five hundred fifty-Three");
        words.add("Five hundred fifty-Four");
        words.add("Five hundred fifty-Five");
        words.add("Five hundred fifty-Six");
        words.add("Five hundred fifty-Seven");
        words.add("Five hundred fifty-Eight");
        words.add("Five hundred fifty-Nine");
        words.add("Five hundred Sixty");
        words.add("Five hundred Sixty-One");
        words.add("Five hundred Sixty-Two");
        words.add("Five hundred Sixty-Three");
        words.add("Five hundred Sixty-Four");
        words.add("Five hundred Sixty-Five");
        words.add("Five hundred Sixty-Six");
        words.add("Five hundred Sixty-Seven");
        words.add("Five hundred Sixty-Eight");
        words.add("Five hundred Sixty-Nine");
        words.add("Five hundred Seventy");
        words.add("Five hundred Seventy-One");
        words.add("Five hundred Seventy-Two");
        words.add("Five hundred Seventy-Three");
        words.add("Five hundred Seventy-Four");
        words.add("Five hundred Seventy-Five");
        words.add("Five hundred Seventy-Six");
        words.add("Five hundred Seventy-Seven");
        words.add("Five hundred Seventy-Eight");
        words.add("Five hundred Seventy-Nine");
        words.add("Five hundred eighty");
        words.add("Five hundred eighty-One");
        words.add("Five hundred eighty-Two");
        words.add("Five hundred eighty-Three");
        words.add("Five hundred eighty-Four");
        words.add("Five hundred eighty-Five");
        words.add("Five hundred eighty-Six");
        words.add("Five hundred eighty-Seven");
        words.add("Five hundred eighty-Eight");
        words.add("Five hundred eighty-Nine");
        words.add("Five hundred Ninety");
        words.add("Five hundred Ninety-One");
        words.add("Five hundred Ninety-Two");
        words.add("Five hundred Ninety-Three");
        words.add("Five hundred Ninety-Four");
        words.add("Five hundred Ninety-Five");
        words.add("Five hundred Ninety-Six");
        words.add("Five hundred Ninety-Seven");
        words.add("Five hundred Ninety-Eight");
        words.add("Five hundred Ninety-Nine");
        words.add("Six hundred");
        words.add("Six hundred One");
        words.add("Six hundred Two");
        words.add("Six hundred Three");
        words.add("Six hundred Four");
        words.add("Six hundred Five");
        words.add("Six hundred Six");
        words.add("Six hundred Seven");
        words.add("Six hundred Eight");
        words.add("Six hundred Nine");
        words.add("Six hundred ten");
        words.add("Six hundred eleven");
        words.add("Six hundred twelve");
        words.add("Six hundred thirteen");
        words.add("Six hundred Fourteen");
        words.add("Six hundred fifteen");
        words.add("Six hundred Sixteen");
        words.add("Six hundred Seventeen");
        words.add("Six hundred eighteen");
        words.add("Six hundred Nineteen");
        words.add("Six hundred twenty");
        words.add("Six hundred twenty-One");
        words.add("Six hundred twenty-Two");
        words.add("Six hundred twenty-Three");
        words.add("Six hundred twenty-Four");
        words.add("Six hundred twenty-Five");
        words.add("Six hundred twenty-Six");
        words.add("Six hundred twenty-Seven");
        words.add("Six hundred twenty-Eight");
        words.add("Six hundred twenty-Nine");
        words.add("Six hundred thirty");
        words.add("Six hundred thirty-One");
        words.add("Six hundred thirty-Two");
        words.add("Six hundred thirty-Three");
        words.add("Six hundred thirty-Four");
        words.add("Six hundred thirty-Five");
        words.add("Six hundred thirty-Six");
        words.add("Six hundred thirty-Seven");
        words.add("Six hundred thirty-Eight");
        words.add("Six hundred thirty-Nine");
        words.add("Six hundred forty");
        words.add("Six hundred forty-One");
        words.add("Six hundred forty-Two");
        words.add("Six hundred forty-Three");
        words.add("Six hundred forty-Four");
        words.add("Six hundred forty-Five");
        words.add("Six hundred forty-Six");
        words.add("Six hundred forty-Seven");
        words.add("Six hundred forty-Eight");
        words.add("Six hundred forty-Nine");
        words.add("Six hundred fifty");
        words.add("Six hundred fifty-One");
        words.add("Six hundred fifty-Two");
        words.add("Six hundred fifty-Three");
        words.add("Six hundred fifty-Four");
        words.add("Six hundred fifty-Five");
        words.add("Six hundred fifty-Six");
        words.add("Six hundred fifty-Seven");
        words.add("Six hundred fifty-Eight");
        words.add("Six hundred fifty-Nine");
        words.add("Six hundred Sixty");
        words.add("Six hundred Sixty-One");
        words.add("Six hundred Sixty-Two");
        words.add("Six hundred Sixty-Three");
        words.add("Six hundred Sixty-Four");
        words.add("Six hundred Sixty-Five");
        words.add("Six hundred Sixty-Six");
        words.add("Six hundred Sixty-Seven");
        words.add("Six hundred Sixty-Eight");
        words.add("Six hundred Sixty-Nine");
        words.add("Six hundred Seventy");
        words.add("Six hundred Seventy-One");
        words.add("Six hundred Seventy-Two");
        words.add("Six hundred Seventy-Three");
        words.add("Six hundred Seventy-Four");
        words.add("Six hundred Seventy-Five");
        words.add("Six hundred Seventy-Six");
        words.add("Six hundred Seventy-Seven");
        words.add("Six hundred Seventy-Eight");
        words.add("Six hundred Seventy-Nine");
        words.add("Six hundred eighty");
        words.add("Six hundred eighty-One");
        words.add("Six hundred eighty-Two");
        words.add("Six hundred eighty-Three");
        words.add("Six hundred eighty-Four");
        words.add("Six hundred eighty-Five");
        words.add("Six hundred eighty-Six");
        words.add("Six hundred eighty-Seven");
        words.add("Six hundred eighty-Eight");
        words.add("Six hundred eighty-Nine");
        words.add("Six hundred Ninety");
        words.add("Six hundred Ninety-One");
        words.add("Six hundred Ninety-Two");
        words.add("Six hundred Ninety-Three");
        words.add("Six hundred Ninety-Four");
        words.add("Six hundred Ninety-Five");
        words.add("Six hundred Ninety-Six");
        words.add("Six hundred Ninety-Seven");
        words.add("Six hundred Ninety-Eight");
        words.add("Six hundred Ninety-Nine");
        words.add("Seven hundred");
        words.add("Seven hundred One");
        words.add("Seven hundred Two");
        words.add("Seven hundred Three");
        words.add("Seven hundred Four");
        words.add("Seven hundred Five");
        words.add("Seven hundred Six");
        words.add("Seven hundred Seven");
        words.add("Seven hundred Eight");
        words.add("Seven hundred Nine");
        words.add("Seven hundred ten");
        words.add("Seven hundred eleven");
        words.add("Seven hundred twelve");
        words.add("Seven hundred thirteen");
        words.add("Seven hundred Fourteen");
        words.add("Seven hundred fifteen");
        words.add("Seven hundred Sixteen");
        words.add("Seven hundred Seventeen");
        words.add("Seven hundred eighteen");
        words.add("Seven hundred Nineteen");
        words.add("Seven hundred twenty");
        words.add("Seven hundred twenty-One");
        words.add("Seven hundred twenty-Two");
        words.add("Seven hundred twenty-Three");
        words.add("Seven hundred twenty-Four");
        words.add("Seven hundred twenty-Five");
        words.add("Seven hundred twenty-Six");
        words.add("Seven hundred twenty-Seven");
        words.add("Seven hundred twenty-Eight");
        words.add("Seven hundred twenty-Nine");
        words.add("Seven hundred thirty");
        words.add("Seven hundred thirty-One");
        words.add("Seven hundred thirty-Two");
        words.add("Seven hundred thirty-Three");
        words.add("Seven hundred thirty-Four");
        words.add("Seven hundred thirty-Five");
        words.add("Seven hundred thirty-Six");
        words.add("Seven hundred thirty-Seven");
        words.add("Seven hundred thirty-Eight");
        words.add("Seven hundred thirty-Nine");
        words.add("Seven hundred forty");
        words.add("Seven hundred forty-One");
        words.add("Seven hundred forty-Two");
        words.add("Seven hundred forty-Three");
        words.add("Seven hundred forty-Four");
        words.add("Seven hundred forty-Five");
        words.add("Seven hundred forty-Six");
        words.add("Seven hundred forty-Seven");
        words.add("Seven hundred forty-Eight");
        words.add("Seven hundred forty-Nine");
        words.add("Seven hundred fifty");
        words.add("Seven hundred fifty-One");
        words.add("Seven hundred fifty-Two");
        words.add("Seven hundred fifty-Three");
        words.add("Seven hundred fifty-Four");
        words.add("Seven hundred fifty-Five");
        words.add("Seven hundred fifty-Six");
        words.add("Seven hundred fifty-Seven");
        words.add("Seven hundred fifty-Eight");
        words.add("Seven hundred fifty-Nine");
        words.add("Seven hundred Sixty");
        words.add("Seven hundred Sixty-One");
        words.add("Seven hundred Sixty-Two");
        words.add("Seven hundred Sixty-Three");
        words.add("Seven hundred Sixty-Four");
        words.add("Seven hundred Sixty-Five");
        words.add("Seven hundred Sixty-Six");
        words.add("Seven hundred Sixty-Seven");
        words.add("Seven hundred Sixty-Eight");
        words.add("Seven hundred Sixty-Nine");
        words.add("Seven hundred Seventy");
        words.add("Seven hundred Seventy-One");
        words.add("Seven hundred Seventy-Two");
        words.add("Seven hundred Seventy-Three");
        words.add("Seven hundred Seventy-Four");
        words.add("Seven hundred Seventy-Five");
        words.add("Seven hundred Seventy-Six");
        words.add("Seven hundred Seventy-Seven");
        words.add("Seven hundred Seventy-Eight");
        words.add("Seven hundred Seventy-Nine");
        words.add("Seven hundred eighty");
        words.add("Seven hundred eighty-One");
        words.add("Seven hundred eighty-Two");
        words.add("Seven hundred eighty-Three");
        words.add("Seven hundred eighty-Four");
        words.add("Seven hundred eighty-Five");
        words.add("Seven hundred eighty-Six");
        words.add("Seven hundred eighty-Seven");
        words.add("Seven hundred eighty-Eight");
        words.add("Seven hundred eighty-Nine");
        words.add("Seven hundred Ninety");
        words.add("Seven hundred Ninety-One");
        words.add("Seven hundred Ninety-Two");
        words.add("Seven hundred Ninety-Three");
        words.add("Seven hundred Ninety-Four");
        words.add("Seven hundred Ninety-Five");
        words.add("Seven hundred Ninety-Six");
        words.add("Seven hundred Ninety-Seven");
        words.add("Seven hundred Ninety-Eight");
        words.add("Seven hundred Ninety-Nine");
        words.add("Eight hundred");
        words.add("Eight hundred One");
        words.add("Eight hundred Two");
        words.add("Eight hundred Three");
        words.add("Eight hundred Four");
        words.add("Eight hundred Five");
        words.add("Eight hundred Six");
        words.add("Eight hundred Seven");
        words.add("Eight hundred Eight");
        words.add("Eight hundred Nine");
        words.add("Eight hundred ten");
        words.add("Eight hundred eleven");
        words.add("Eight hundred twelve");
        words.add("Eight hundred thirteen");
        words.add("Eight hundred Fourteen");
        words.add("Eight hundred fifteen");
        words.add("Eight hundred Sixteen");
        words.add("Eight hundred Seventeen");
        words.add("Eight hundred eighteen");
        words.add("Eight hundred Nineteen");
        words.add("Eight hundred twenty");
        words.add("Eight hundred twenty-One");
        words.add("Eight hundred twenty-Two");
        words.add("Eight hundred twenty-Three");
        words.add("Eight hundred twenty-Four");
        words.add("Eight hundred twenty-Five");
        words.add("Eight hundred twenty-Six");
        words.add("Eight hundred twenty-Seven");
        words.add("Eight hundred twenty-Eight");
        words.add("Eight hundred twenty-Nine");
        words.add("Eight hundred thirty");
        words.add("Eight hundred thirty-One");
        words.add("Eight hundred thirty-Three");
        words.add("Eight hundred thirty-Two");
        words.add("Eight hundred thirty-Four");
        words.add("Eight hundred thirty-Five");
        words.add("Eight hundred thirty-Six");
        words.add("Eight hundred thirty-Seven");
        words.add("Eight hundred thirty-Eight");
        words.add("Eight hundred thirty-Nine");
        words.add("Eight hundred forty");
        words.add("Eight hundred forty-One");
        words.add("Eight hundred forty-Two");
        words.add("Eight hundred forty-Three");
        words.add("Eight hundred forty-Four");
        words.add("Eight hundred forty-Five");
        words.add("Eight hundred forty-Six");
        words.add("Eight hundred forty-Seven");
        words.add("Eight hundred forty-Eight");
        words.add("Eight hundred forty-Nine");
        words.add("Eight hundred fifty");
        words.add("Eight hundred fifty-One");
        words.add("Eight hundred fifty-Two");
        words.add("Eight hundred fifty-Three");
        words.add("Eight hundred fifty-Four");
        words.add("Eight hundred fifty-Five");
        words.add("Eight hundred fifty-Six");
        words.add("Eight hundred fifty-Seven");
        words.add("Eight hundred fifty-Eight");
        words.add("Eight hundred fifty-Nine");
        words.add("Eight hundred Sixty");
        words.add("Eight hundred Sixty-One");
        words.add("Eight hundred Sixty-Two");
        words.add("Eight hundred Sixty-Three");
        words.add("Eight hundred Sixty-Four");
        words.add("Eight hundred Sixty-Five");
        words.add("Eight hundred Sixty-Six");
        words.add("Eight hundred Sixty-Seven");
        words.add("Eight hundred Sixty-Eight");
        words.add("Eight hundred Sixty-Nine");
        words.add("Eight hundred Seventy");
        words.add("Eight hundred Seventy-One");
        words.add("Eight hundred Seventy-Two");
        words.add("Eight hundred Seventy-Three");
        words.add("Eight hundred Seventy-Four");
        words.add("Eight hundred Seventy-Five");
        words.add("Eight hundred Seventy-Six");
        words.add("Eight hundred Seventy-Seven");
        words.add("Eight hundred Seventy-Eight");
        words.add("Eight hundred Seventy-Nine");
        words.add("Eight hundred eighty");
        words.add("Eight hundred eighty-One");
        words.add("Eight hundred eighty-Two");
        words.add("Eight hundred eighty-Three");
        words.add("Eight hundred eighty-Four");
        words.add("Eight hundred eighty-Five");
        words.add("Eight hundred eighty-Six");
        words.add("Eight hundred eighty-Seven");
        words.add("Eight hundred eighty-Eight");
        words.add("Eight hundred eighty-Nine");
        words.add("Eight hundred Ninety");
        words.add("Eight hundred Ninety-One");
        words.add("Eight hundred Ninety-Two");
        words.add("Eight hundred Ninety-Three");
        words.add("Eight hundred Ninety-Four");
        words.add("Eight hundred Ninety-Five");
        words.add("Eight hundred Ninety-Six");
        words.add("Eight hundred Ninety-Seven");
        words.add("Eight hundred Ninety-Eight");
        words.add("Eight hundred Ninety-Nine");
        words.add("Nine hundred");
        words.add("Nine hundred One");
        words.add("Nine hundred Two");
        words.add("Nine hundred Three");
        words.add("Nine hundred Four");
        words.add("Nine hundred Five");
        words.add("Nine hundred Six");
        words.add("Nine hundred Seven");
        words.add("Nine hundred Eight");
        words.add("Nine hundred Nine");
        words.add("Nine hundred ten");
        words.add("Nine hundred eleven");
        words.add("Nine hundred twelve");
        words.add("Nine hundred thirteen");
        words.add("Nine hundred Fourteen");
        words.add("Nine hundred fifteen");
        words.add("Nine hundred Sixteen");
        words.add("Nine hundred Seventeen");
        words.add("Nine hundred eighteen");
        words.add("Nine hundred Nineteen");
        words.add("Nine hundred twenty");
        words.add("Nine hundred twenty-One");
        words.add("Nine hundred twenty-Two");
        words.add("Nine hundred twenty-Three");
        words.add("Nine hundred twenty-Four");
        words.add("Nine hundred twenty-Five");
        words.add("Nine hundred twenty-Six");
        words.add("Nine hundred twenty-Seven");
        words.add("Nine hundred twenty-Eight");
        words.add("Nine hundred twenty-Nine");
        words.add("Nine hundred thirty");
        words.add("Nine hundred thirty-One");
        words.add("Nine hundred thirty-Two");
        words.add("Nine hundred thirty-Three");
        words.add("Nine hundred thirty-Four");
        words.add("Nine hundred thirty-Five");
        words.add("Nine hundred thirty-Six");
        words.add("Nine hundred thirty-Seven");
        words.add("Nine hundred thirty-Eight");
        words.add("Nine hundred thirty-Nine");
        words.add("Nine hundred forty");
        words.add("Nine hundred forty-One");
        words.add("Nine hundred forty-Two");
        words.add("Nine hundred forty-Three");
        words.add("Nine hundred forty-Four");
        words.add("Nine hundred forty-Five");
        words.add("Nine hundred forty-Six");
        words.add("Nine hundred forty-Seven");
        words.add("Nine hundred forty-Eight");
        words.add("Nine hundred forty-Nine");
        words.add("Nine hundred fifty");
        words.add("Nine hundred fifty-One");
        words.add("Nine hundred fifty-Two");
        words.add("Nine hundred fifty-Three");
        words.add("Nine hundred fifty-Four");
        words.add("Nine hundred fifty-Five");
        words.add("Nine hundred fifty-Six");
        words.add("Nine hundred fifty-Seven");
        words.add("Nine hundred fifty-Eight");
        words.add("Nine hundred fifty-Nine");
        words.add("Nine hundred Sixty");
        words.add("Nine hundred Sixty-One");
        words.add("Nine hundred Sixty-Two");
        words.add("Nine hundred Sixty-Three");
        words.add("Nine hundred Sixty-Four");
        words.add("Nine hundred Sixty-Five");
        words.add("Nine hundred Sixty-Six");
        words.add("Nine hundred Sixty-Seven");
        words.add("Nine hundred Sixty-Eight");
        words.add("Nine hundred Sixty-Nine");
        words.add("Nine hundred Seventy");
        words.add("Nine hundred Seventy-One");
        words.add("Nine hundred Seventy-Two");
        words.add("Nine hundred Seventy-Three");
        words.add("Nine hundred Seventy-Four");
        words.add("Nine hundred Seventy-Five");
        words.add("Nine hundred Seventy-Six");
        words.add("Nine hundred Seventy-Seven");
        words.add("Nine hundred Seventy-Eight");
        words.add("Nine hundred Seventy-Nine");
        words.add("Nine hundred eighty");
        words.add("Nine hundred eighty-One");
        words.add("Nine hundred eighty-Two");
        words.add("Nine hundred eighty-Three");
        words.add("Nine hundred eighty-Four");
        words.add("Nine hundred eighty-Five");
        words.add("Nine hundred eighty-Six");
        words.add("Nine hundred eighty-Seven");
        words.add("Nine hundred eighty-Eight");
        words.add("Nine hundred eighty-Nine");
        words.add("Nine hundred Ninety");
        words.add("Nine hundred Ninety-One");
        words.add("Nine hundred Ninety-Two");
        words.add("Nine hundred Ninety-Three");
        words.add("Nine hundred Ninety-Four");
        words.add("Nine hundred Ninety-Five");
        words.add("Nine hundred Ninety-Six");
        words.add("Nine hundred Ninety-Seven");
        words.add("Nine hundred Ninety-Eight");
        words.add("Nine hundred Ninety-Nine");
        words.add("One Thousand");

        // find the root view of the whole layout
        LinearLayout rootView =(LinearLayout)findViewById(R.id.rootView);

        int index =0;

        while(index<words.size()){
            // Create a new {@link TextView} that displayed that word at each element
            // and add the view as a child to the rootView
            TextView wordView = new TextView(this);
            wordView.setText(words.get(index));
            rootView.addView(wordView);

            //Update counter variable
            index++;
        }

    }
}